name    'evgeni-nginx'
version '0.0.1'
source 'http://github.com/evgeni/puppet-nginx'
author 'evgeni'
license 'Apache License, Version 2.0'
summary 'yet another nginx module'
description 'UNKNOWN'
project_page 'http://github.com/evgeni/puppet-nginx'

dependency 'puppetlabs/stdlib', '>= 2.3.0'
